# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.4.4

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Persistent GHC powered background server for FAST haskell development tools"
HOMEPAGE="https://github.com/bitc/hdevtools/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
#KEYWORDS="~amd64 ~x86"
# well, I quit. Just hope someone can fix it
KEYWORDS=""
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
	dev-haskell/cmdargs
	>=dev-lang/ghc-7.2
	dev-haskell/ghc-paths
	dev-haskell/network
	dev-haskell/syb
"
